import {createCipheriv,createDecipheriv,createHash,randomBytes} from "node:crypto";

const tokenUrl="https://oauth2.googleapis.com/token";
function required(name:"GOOGLE_CLIENT_ID"|"GOOGLE_CLIENT_SECRET"){const value=process.env[name];if(!value)throw new Error(`${name} belum dikonfigurasi`);return value}
function encryptionKey(){return createHash("sha256").update(required("GOOGLE_CLIENT_SECRET")).digest()}

export function encryptDriveToken(value:string){const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",encryptionKey(),iv);const encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return[iv.toString("base64url"),cipher.getAuthTag().toString("base64url"),encrypted.toString("base64url")].join(".")}
export function decryptDriveToken(value:string){const[iv,tag,payload]=value.split(".");if(!iv||!tag||!payload)throw new Error("Token Drive tidak valid");const decipher=createDecipheriv("aes-256-gcm",encryptionKey(),Buffer.from(iv,"base64url"));decipher.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([decipher.update(Buffer.from(payload,"base64url")),decipher.final()]).toString("utf8")}
export function googleRedirectUri(origin:string){return process.env.GOOGLE_REDIRECT_URI||`${origin}/api/integrations/google/callback`}
export function googleAuthorizationUrl({state,redirectUri}:{state:string;redirectUri:string}){const params=new URLSearchParams({client_id:required("GOOGLE_CLIENT_ID"),redirect_uri:redirectUri,response_type:"code",access_type:"offline",prompt:"consent",scope:"openid email https://www.googleapis.com/auth/drive.file",state});return`https://accounts.google.com/o/oauth2/v2/auth?${params}`}

export async function exchangeGoogleCode(code:string,redirectUri:string){const response=await fetch(tokenUrl,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:required("GOOGLE_CLIENT_ID"),client_secret:required("GOOGLE_CLIENT_SECRET"),redirect_uri:redirectUri,grant_type:"authorization_code"}),cache:"no-store"});const result=await response.json() as {access_token?:string;refresh_token?:string;error_description?:string};if(!response.ok||!result.access_token)throw new Error(result.error_description||"Google gagal memberikan akses");return result}
export async function createDriveFolder(accessToken:string,eventName:string){const folderName=`Kapsul — ${eventName}`;const response=await fetch("https://www.googleapis.com/drive/v3/files?fields=id,name",{method:"POST",headers:{authorization:`Bearer ${accessToken}`,"content-type":"application/json"},body:JSON.stringify({name:folderName,mimeType:"application/vnd.google-apps.folder"}),cache:"no-store"});const result=await response.json() as {id?:string;name?:string;error?:{message?:string}};if(!response.ok||!result.id)throw new Error(result.error?.message||"Folder Google Drive gagal dibuat");return{id:result.id,name:result.name||folderName}}
export async function getGoogleAccountEmail(accessToken:string){const response=await fetch("https://openidconnect.googleapis.com/v1/userinfo",{headers:{authorization:`Bearer ${accessToken}`},cache:"no-store"});if(!response.ok)return null;const result=await response.json() as {email?:string};return result.email||null}
